version: '3.9'
services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE:-modx}
      - MARIADB_USER=${MARIADB_USERNAME:-modx}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-modx}
      - TZ=${TZ:-Europe/Zurich}
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    working_dir: /modx

  nginx:
    image: nginx:${NGINX_VERSION:-1.25}
    environment:
      - NGINX_PORT=${NGINX_PORT:-8080}
      - TZ=${TZ:-Europe/Zurich}
    volumes:
      - ./nginx:/etc/nginx/templates
      - ../modx:/modx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
      - mariadb
    working_dir: /modx

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
        - PHP_XDEBUG=${PHP_XDEBUG:-1}
        - TZ=${TZ:-Europe/Zurich}
    volumes:
      - ./.env:/modx/.env
      - ../modx:/modx
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG="serverName=ModxDocker"
    working_dir: /modx

  node:
    image: node:${NODE_VERSION:-21}
    environment:
      - TZ=${TZ:-Europe/Zurich}
    volumes:
      - ../assets:/assets
      - ../modx:/modx
    ports:
      - ${NODE_DEV_PORT:-9090}:9090
    depends_on:
      - nginx
    working_dir: /assets
    command: sh -c "yarn && yarn dev"